pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge on CI success
    conditions:
      - status-success=ci/circleci
    actions:
      merge:
        method: merge
        strict: true
